# site name
prefixName: iMouup
siteName: 拉米雷斯
# favicon and site master avatar
favicon: https://cdn.jsdelivr.net/gh/imouup/pic/20201107_104156023_iOS.jpg
avatar: https://cdn.jsdelivr.net/gh/imouup/pic/20201107_104156023_iOS.jpg
url: https://mouup.top
description: 没错就是我（￣︶￣）↗　Mouup
cdn:
pjax: 1
# 1开启
mathjax: 0

notice: hello
lazyloadImg: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/loader/orange.progress-bar-stripe-loader.svg
#seo优化设定
seo:
  #网站简介
  description: 拉米雷斯的个人博客
  #关键词
  keywords: Mouup,iMouup,Linux,拉米雷斯w,拉米雷斯，lmlsw,Sakura
menus:
  首页: { path: /, fa: fa-fort-awesome faa-shake }
  归档: { path: /archives, fa: far fa-folder-open, submenus: { 
    技术: {path: /categories/技术/, fa: fab fa-windows }, 
    生活: {path: /categories/生活/, fa: fa-book }, 
    资源: {path: /categories/资源/, fa: fa-cloud-download }, 
    随想: {path: /categories/随想/, fa: fa-commenting-o },
    转载: {path: /categories/转载/, fa: fas fa-clone }
  } }
  清单: { path: javascript:;, fa: fa-list-ul faa-vertical, submenus: {
    书单: {path: /tags/悦读/, fa: fa-th-list faa-bounce },
    番组: {path: /bangumi/, fa: fa-film faa-vertical },
    歌单: {path: /music/, fa: fa-headphones },
    图集: {path: /tags/图集/, fa: fa-photo }
  } }
  留言板: { path: /comment/, fa: fa-pencil-square-o faa-tada }
  #标签: {path: /tags }
  #赞赏: { path: /donate/, fa: fa-heart faa-pulse }
  关于: { path: /, fa: fa-leaf faa-wrench , submenus: {
    我？: {path: /about/, fa: fa-meetup},
    主题: {path: /theme-sakura/, fa: iconfont icon-sakura },
    Lab: {path: /lab/, fa: fa-cogs },
  } }
  #客户端: { path: /client/, fa: fa-android faa-vertical }
  友人帐: { path: /links/, fa: fa-link faa-shake }
  #RSS: { path: /atom.xml, fa: fa-rss faa-pulse }

#页脚信息
pagefooter: "&copy 2021Mouup"

# Home page sort type: -1: newer first，1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 10
# 背景图片 更好的修改
bg: https://api.vvhan.com/api/acgimg
  

# 背景图片样式 空 原图效果 filter-dim 阴影 filter-grid 横条 filter-dot 点点
bgclass: filter-dim

# startdash url, title, desc img
startdash:
  - {url: https://github.com/imouup, title: Github , desc: my github, img: https://cdn.jsdelivr.net/gh/imouup/pic/0.jpg}
  - {url: https://space.bilibili.com/438518095, title: Bilibili, desc: up的b站视频, img: https://cdn.jsdelivr.net/gh/imouup/pic/20200717_023317282_iOS.jpg}
  - {url: https://www.zhihu.com/people/gui-ling-zhe-92, title: 知乎, desc: 知乎, img: https://cdn.jsdelivr.net/gh/imouup/pic/20200505_102236910_iOS 1.jpg}


# your site build time or founded date (建站日期）
siteBuildingTime: 2021-1-27
#页脚显示网站已运行时间
runtime: true

#social  url, img PC端配置
social:
  github: {url: http://github.com/imouup, img: https://cdn.jsdelivr.net/gh/xbclub/staticCDN@0.6/img/social/github.png}
  #sina: {url: http://weibo.com/mashirozx?is_all=1, img: /img/social/sina.png}
  #wangyiyun: {url: http://weibo.com/mashirozx?is_all=1, img: /img/social/wangyiyun.png}
  zhihu: {url: https://www.zhihu.com/people/gui-ling-zhe-92, img: https://cdn.jsdelivr.net/gh/imouup/pic/知乎.png}
  #email: {url: iamswlx@outlook.com, img: https://cdn.jsdelivr.net/gh/xbclub/staticCDN@0.6/img/social/email.svg}
  #wechat: {url: /#, qrcode: /img/custom/wechat.jpg, img: /img/social/wechat.png}
  bilibili: {url: https://space.bilibili.com/438518095, img: https://cdn.jsdelivr.net/gh/imouup/pic/bilibili-line.png}
  Twitter: {url: https://twitter.com/Mouupsw, img: https://cdn.jsdelivr.net/gh/imouup/pic/推特.png}

#social  url, img 移动端配置
msocial:
  github: {url:  http://github.com/imouup, fa: fa-github, color: 333}
#  weibo: {url: http://weibo.com/mashirozx?is_all=1, fa: fa-weibo, color: dd4b39}
  #qq: {url: https://wpa.qq.com/msgrd?v=3&uin=525255289&site=qq&menu=yes, fa: fa-qq, color: 25c6fe}

donate:
  switch: true
  #paypal: https://www.paypal.me/
  alipay: https://cdn.jsdelivr.net/gh/imouup/pic/pic/微信图片_20210205120713.jpg
  wechat: https://cdn.jsdelivr.net/gh/imouup/pic/pic/微信图片_20210205120735.jpg
  #wechatSQ: /img/custom/donate/WeChanSQ.jpg

# 视频地址为https://cdn.jsdelivr.net/gh/honjun/hojun@1.2/Unbroken.mp4，配置如下
movies:
  switch: true
  url: https://onedrive.gimhoy.com/sharepoint/aHR0cHM6Ly9pYW1zd2x4LW15LnNoYXJlcG9pbnQuY29tLzp2Oi9nL3BlcnNvbmFsL2lhbXN3bHhfaWFtc3dseF9vbm1pY3Jvc29mdF9jb20vRWFPeUtmQ0dRUmxEcThqUkVKS1FkeThCOVh5djhUNVZTWl9va2tZdFhWQWNXUT9lPXBkUTB4SQ==.mp4
  # 多个视频用逗号隔开，随机获取。支持的格式目前已知MP4,Flv。其他的可以试下，不保证有用
  name: vides.mp4

aplayer:
  switch: true
  id: 5484942041
  server: netease
  type: playlist
  fixed: true
  autoplay: false
  loop: all
  order: random
  preload: auto
  volume: 0.7
  mutex: true

# Valine
valine: true
v_appId: FsiFpA3rJtzbgfaicI9waUSh-MdYXbMMI
v_appKey: lS5Xp47iS7OG0172dfKN2Cqk


# 计数器
readcounts: true

#不蒜子计数器
busuanzi:
  switch: false

#每日一言
hitokoto: true

#全站灰白主题
gray: false

#剪贴板版权
clipboards: false

dark_mode:
  enable: flase

googleAnalytics:
  enable: true
  id: G-0FMX7K7FR0

baiduAnalytics:
  enable: true # 百度分析
  id: e2618b6872637968aaf29fd295088ecb